name: BungeePEX
main: com.xaosia.bungeepex.platform.bukkit.BukkitPlugin
version: 1.0.0
author: XAOS-IA
load: STARTUP

commands:
    bungeepexsbukkitbridge:
        description: base command
        aliases: bpexbb
    bungeepexbukkitbridge reload:
        description: reinjects BungeePEX into all found/supported plugins
        